name: salebook
description: "Smart Sales Tracker"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Speech Recognition (with built-in cloud/local switching)
  speech_to_text: ^7.0.0

  # Permissions
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  get: ^4.6.6
  device_info_plus: ^10.1.0

flutter:
  uses-material-design: true